service: valkFly-backend

plugins:
  - serverless-bundle 
  - serverless-iam-roles-per-function

custom: 
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: us-east-1
  versionFunctions: false
  environment:
    usersTableDynamoName: ${self:service}-${self:custom.stage}-users
    serviceName: ${self:service}

package:
  exclude:
    - .serverless/**
    - .git/**
    - node_modules/**

functions:
  - ${file(sls/functions/lambda.yml)}
  - ${file(sls/functions/authorizer.yml)}


resources:
  - ${file(sls/resources/dynamodb/usersTable.yml)}
  - ${file(sls/resources/cognitoUser/cognito-user-pool.yml)}
  - ${file(sls/resources/cognitoIdentity/cognito-user-pool.yml)}
