service: valkFly-backend

plugins:
  - serverless-bundle 
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  versionFunctions: false
  environment:
    usersTableDynamo: ${self:service}-users
    serviceName: ${self:service}

package:
  exclude:
    - .serverless/**
    - .git/**
    - node_modules/**

functions:
  - ${file(sls/functions/lambda.yml)}


resources:
  - ${file(sls/resources/dynamodb/usersTable.yml)}
