service: ${self:custom.serviceName}

plugins:
  - serverless-bundle 
  - serverless-iam-roles-per-function

custom: 
  stage: ${opt:stage, 'dev'}
  serviceName: valkFly-backend

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  versionFunctions: false
  environment:
    stage: ${self:custom.stage}
    serviceName: ${self:custom.serviceName}
    usersTableDynamoName:  ${self:custom.serviceName}-${self:custom.stage}-users
    collectionsTableDynamoName:  ${self:custom.serviceName}-${self:custom.stage}-collections

package:
  exclude:
    - .serverless/**
    - .git/**
    - node_modules/**

functions:
  - ${file(sls/functions/lambda.yml)}
  - ${file(sls/functions/authorizer.yml)}


resources:
  # dynamo
  - ${file(sls/resources/dynamodb/usersTable.yml)}
  - ${file(sls/resources/dynamodb/projectsTable.yml)}
