service: ${self:custom.serviceName}

plugins:
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function
  - serverless-bundle

custom:
  stage: ${opt:stage, 'dev'}
  serviceName: valkyrie-backend

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  environment:
    stage: ${self:custom.stage}
    serviceName: ${self:custom.serviceName}
    region: us-east-1
    imagesTableDynamoName: ${self:custom.serviceName}-${self:custom.stage}-images
    projectsTableDynamoName: ${self:custom.serviceName}-${self:custom.stage}-projects
    imagesBucketName: ${self:service}-${self:custom.stage}-images-bucket
    email: valkyrie.cesupa@gmail.com
    cognitoUserPoolId: us-east-1_viDR20etW

package:
  exclude:
    - .serverless/**
    - .git/**
    - node_modules/**

functions:
  - ${file(sls/functions/projects.yml)}
  - ${file(sls/functions/images.yml)}

resources:
  # dynamo
  - ${file(sls/resources/dynamodb/imagesTable.yml)}
  - ${file(sls/resources/dynamodb/projectsTable.yml)}

  # Cognito
  - ${file(sls/resources/cognitoUser/cognito-user-pool.yml)}
  - ${file(sls/resources/cognitoIdentity/cognito-identity-pool.yml)}

  # S3
  - ${file(sls/resources/s3/imagesBucket.yml)}
