service: ${self:custom.serviceName}

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function

custom:
  stage: ${opt:stage, 'dev'}
  serviceName: valkFly-backend

# Isso serve para facilitar o import, invés de você fazer isso import * from '../src/models' pode ser assim import * from 'Models';
aliases:
  - Models: src/models
  - Utils: src/utils

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  versionFunctions: false
  environment:
    stage: ${self:custom.stage}
    serviceName: ${self:custom.serviceName}
    usersTableDynamoName: ${self:custom.serviceName}-${self:custom.stage}-users
    imagesTableDynamoName: ${self:custom.serviceName}-${self:custom.stage}-images
    projectsTableDynamoName: ${self:custom.serviceName}-${self:custom.stage}-projects

package:
  exclude:
    - .serverless/**
    - .git/**
    - node_modules/**

functions:
  - ${file(sls/functions/lambda.yml)}
  - ${file(sls/functions/authorizer.yml)}
  - ${file(sls/functions/projects.yml)}

resources:
  # dynamo
  - ${file(sls/resources/dynamodb/usersTable.yml)}
  - ${file(sls/resources/dynamodb/imagesTable.yml)}
  - ${file(sls/resources/dynamodb/projectsTable.yml)}
  - ${file(sls/resources/cognitoUser/cognito-user-pool.yml)}
  - ${file(sls/resources/cognitoIdentity/cognito-identity-pool.yml)}
