Resources:
  imagesTableDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.imagesTableDynamoName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: collectionId
          AttributeType: S
        - AttributeName: response
          AttributeType: S
        - AttributeName: S3Link
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: updatedAt
          AttributeType: S
        - AttributeName: deletedAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName:  CollectionIdCreatedAtIndex
          KeySchema:
            - AttributeName: collectionId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
        - IndexName:  CollectionIdImageIdIndex
          KeySchema:
            - AttributeName: collectionId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
        - IndexName:  imageIdCreatedIndex
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
      BillingMode: PAY_PER_REQUEST 