Resources:
  imagesTableDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.imagesTableDynamoName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
          Projection:
            ProjectionType: ALL
        - IndexName:  ProjectImage
          KeySchema:
            - AttributeName: ProjectId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName:  ImageDate
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST 